# general
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -s escape-time 0
set -g focus-events on
set -g status-position top

# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# splits
unbind '"'
unbind %
bind-key -n M-s split-window -v -c "#{pane_current_path}"
bind-key -n M-v split-window -h -c "#{pane_current_path}"
bind-key -n M-o new-window -c "#{pane_current_path}"


# pane navigation
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R


# pane moving (swap)
bind-key -n M-H swap-pane -t "{left-of}"
bind-key -n M-J swap-pane -t "{down-of}"
bind-key -n M-K swap-pane -t "{up-of}"
bind-key -n M-L swap-pane -t "{right-of}"


# pane resizing
bind-key -n M-Left  resize-pane -L 5
bind-key -n M-Down  resize-pane -D 5
bind-key -n M-Up    resize-pane -U 5
bind-key -n M-Right resize-pane -R 5


# pane management
bind-key -n M-q kill-pane
bind-key -n M-z resize-pane -Z


# window navigation
bind-key -n M-n next-window
bind-key -n M-p previous-window


# copy mode
set -g mode-keys vi

bind-key -n M-Enter copy-mode
bind -T copy-mode-vi v     send -X begin-selection
bind -T copy-mode-vi y     send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H     send -X start-of-line
bind -T copy-mode-vi L     send -X end-of-line


# plugins
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'


# reload
bind-key -n M-r source-file ~/.config/tmux/tmux.conf \; display "reloaded"
